routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', function () {
    return redirect()->route('jogo.graficos_home');
})->middleware('auth');

Route::get('/home', function () {
    return view('admin/home');
})->middleware('auth');

Route::get('admin/home', function () {
    return redirect()->route('jogo.graficos_home');
})->middleware('auth');

Route::get('admin/idiomas', function () {
    return redirect()->route('idiomas.index');
})->middleware('auth');

Route::get('admin/categorias', function () {
    return redirect()->route('categoria.index');
})->middleware('auth');

Route::get('admin/desenvolvedora', function () {
    return redirect()->route('desenvolvedora.index');
})->middleware('auth');

Route::get('admin/jogo', function () {
    return redirect()->route('jogo.create');
})->middleware('auth');

Route::get('admin/listagem_jogo', function() {
    return redirect()->route('jogo.index');
})->middleware('auth');

Route::get('admin/rel', function() {
    return redirect()->route('jogo.reljogos');
});

Route::post('admin/add_idioma_jogo', 'JogoController@add_idioma')->name('jogo.add_idioma')->middleware('auth');
Route::post('admin/add_categoria_jogo', 'JogoController@add_categoria')->name('jogo.add_categoria')->middleware('auth');
Route::get('admin/home_graficos', 'JogoController@home_graficos')->name('jogo.graficos_home')->middleware('auth');
Route::get('admin/relatorio', 'JogoController@reljogos')->name('jogo.reljogos')->middleware('auth');

Route::resource('jogo', 'JogoController')->middleware('auth');
Route::resource('idiomas', 'IdiomaController')->middleware('auth');
Route::resource('categoria', 'CategoriaController')->middleware('auth');
Route::resource('desenvolvedora', 'DesenvolvedoraController')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------

Route::get('/email', 'MailController@enviaEmail');

Route::get('/site', 'CommerceController@index')->name('site.index');
Route::post('/site/insere', 'CommerceController@insere')->name('site.insere');

Route::get('compra/{id}', 'CommerceController@compra')->where(['id' => '[0-9]+'])->name('site.compra');
Route::get('pesquisa', 'CommerceController@pesquisa')->name('site.pesquisa');

Route::get('/commerce', function() {
    return redirect()->route('site.index');
});

resources/views/admin/cadastro_jogo.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames - Jogo')

@section('content_header')

@endsection

@section('content')

    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <h1 style="text-align: center">Jogos</h1>

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <h3>Cadastro de Jogos</h3>
    <form method="post" action="{{ route('jogo.store') }}" enctype="multipart/form-data">
        {{ csrf_field() }}
        
        <div class="row">
            <div class="col-sm-6">
                <label for="titulo">Título:</label>
                <div class="form-group">
                    <input type="text" class="form-control" id="titulo" name="titulo">
                </div>
            </div>
            <div class="col-sm-6">
                <label for="nome">Desenvolvedor:</label>
                <select class="form-control" 
                            id="desenvolvedor_id" name="desenvolvedor_id">
                    @foreach ($desenvolvedores as $desenvolvedor)
                        <option value="{{$desenvolvedor->id}}">
                            {{$desenvolvedor->nome}}
                        </option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-4">
                <label for="preco">Preço:</label>
                <div class="form-group">
                    <input type="text" class="form-control" id="preco" name="preco">
                </div>
            </div>
            <div class="col-sm-4">
                <label for="foto">Foto:</label>
                <div class="form-group">
                    <input type="file" class="form-control" id="foto" name="foto">
                </div>
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-primary" style="float: right" value="Adicionar">
            </div>
        </div>
        
    </form>
  </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#preco').mask('#.###.##0,00', {reverse: true});
    });
  </script>  
@endsection

resources/views/admin/categoria.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames - Categorias')

@section('content_header')

@endsection

@section('content')
    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <h1 style="text-align: center">Categorias</h1>

    <h3>Inclusão de Categorias</h3>
    <form method="post" action="{{ route('categoria.store') }}">
        {{ csrf_field() }}
        <label for="nome">Nome:</label>
        <div class="row">
            <div class="col-sm-10">
                <div class="form-group">
                    <input type="text" class="form-control" id="nome" name="nome">
                </div>
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-warning" style="float: right" value="Adicionar">
            </div>
        </div>
    </form>


    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>CATEGORIA</th>
        <th>AÇÕES</th>
      </tr>
    </thead>
    <tbody>
      
      @foreach ($categoriasDB as $categoria)
        <tr>
          <td>{{$categoria->id}}</td>
          <td>{{$categoria->nome}}</td>
          <td>
            <form method="post" action="{{ route('categoria.destroy', $categoria->id)}}" style="display: inline-block" 
              onsubmit="return confirm('Confirma Exclusão do idioma?')">          
              {{ method_field('delete') }}
              {{ csrf_field() }}
            <input type="submit" class="btn btn-danger btn-sm" value="Excluir">
            </form>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
  </div>
  <div class="col-sm-2"></div>

@endsection

resources/views/admin/desenvolvedoras.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames - Categorias')

@section('content_header')

@endsection

@section('content')
    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <h1 style="text-align: center; ">Desenvolvedoras</h1>

    <h3>Inclusão de Desenvolvedoras</h3>
    <form method="post" action="{{ route('desenvolvedora.store') }}">
        {{ csrf_field() }}
        <label for="nome">Nome:</label>
        <div class="row">
            <div class="col-sm-10">
                <div class="form-group">
                    <input type="text" class="form-control" id="nome" name="nome">
                </div>
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-warning" value="Adicionar">
            </div>
        </div>
    </form>


    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>NOME</th>
        <th>AÇÕES</th>
      </tr>
    </thead>
    <tbody>
      
      @foreach ($desenvolvedorasDB as $desenvolvedora)
        <tr>
          <td>{{$desenvolvedora->id}}</td>
          <td>{{$desenvolvedora->nome}}</td>
          <td>
            <form method="post" action="{{ route('desenvolvedora.destroy', $desenvolvedora->id)}}" style="display: inline-block" 
              onsubmit="return confirm('Confirma Exclusão da Desenvolvedora?')">          
              {{ method_field('delete') }}
              {{ csrf_field() }}
            <input type="submit" class="btn btn-danger btn-sm" style="float: right" value="Excluir">
            </form>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
  </div>
  <div class="col-sm-2"></div>

@endsection

resources/views/admin/home.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames')

@section('content_header')

@endsection

@section('content')

    <h1 style="text-align: center">Bem vindo {{Auth::user()->name}}</h1>
    <div class="container">
        <div class="col-sm-6">
            <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
            <script type="text/javascript">
            google.charts.load("current", {packages:["corechart"]});
            google.charts.setOnLoadCallback(drawChart);

            function drawChart() {
                var data = google.visualization.arrayToDataTable([['Desenvolvedora', 'Nº de Jogos'],
                    @foreach ($jogos as $jogo)
                        {!! "['$jogo->dev', $jogo->num]," !!}
                    @endforeach
                ]);
                var options = {
                    title: 'Nº de Jogos por Desenvolvedor',
                    is3D: true,
                };
                var chart = new google.visualization
                .PieChart(document.getElementById('piechart_3d'));
                chart.draw(data, options);
            }
            </script>
            <div id="piechart_3d" style="width: 100%; height: 400px"></div>
        </div>

        <div class="col-sm-6">
            <html>
                <head>
                    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
                    <script type="text/javascript">
                    google.charts.load('current', {'packages':['table']});
                    google.charts.setOnLoadCallback(drawTable);

                    function drawTable() {
                        var data = new google.visualization.DataTable();
                        data.addColumn('string', 'Nome');
                        data.addColumn('number', 'Valor de Compra');
                        data.addColumn('boolean', 'Pago');
                        data.addRows([

                            @foreach ($vendas as $venda)
                                {!! "['$venda->nome', {v: $venda->preco, f: '$venda->preco'}, true]," !!}
                            @endforeach

                        ]);

                        var table = new google.visualization.Table(document.getElementById('table_div'));

                        table.draw(data, {showRowNumber: true, width: '100%', height: '100%'});
                    }
                    </script>
                </head>
            <body>
            <div id="table_div"></div>
            </body>
            </html>
        </div>
    </div>

@endsection

resources/views/admin/idioma.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames - Idiomas')

@section('content_header')

@endsection

@section('content')
    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
    <h1 style="text-align: center">Idiomas</h1>

    <h3>Inclusão de Idiomas</h3>
    <form method="post" action="{{ route('idiomas.store') }}">
        {{ csrf_field() }}
        <label for="nome">Nome do Idioma:</label>
        <div class="row">
            <div class="col-sm-10">
                <div class="form-group">
                    <input type="text" class="form-control" id="nome" name="nome">
                </div>
            </div>
            <div class="col-sm-2">
                <input type="submit" class="btn btn-warning" style="float: right" value="Adicionar">
            </div>
        </div>
    </form>


    <table class="table">
    <thead class="thead-dark">
      <tr>
        <th>ID</th>
        <th>IDIOMA</th>
        <th>AÇÕES</th>
      </tr>
    </thead>
    <tbody>
      
      @foreach ($idiomasDB as $idioma)
        <tr>
          <td>{{$idioma->id}}</td>
          <td>{{$idioma->nome}}</td>
          <td>
            <form method="post" action="{{ route('idiomas.destroy', $idioma->id)}}" style="display: inline-block" 
              onsubmit="return confirm('Confirma Exclusão do idioma?')">          
              {{ method_field('delete') }}
              {{ csrf_field() }}
            <input type="submit" class="btn btn-danger btn-sm" value="Excluir">
            </form>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
  </div>
  <div class="col-sm-2"></div>
@endsection

resources/views/admin/listagem_jogo.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames - Jogo')

@section('content_header')

@endsection

@section('content')

    <div class="tela">
    <h1>Jogos Disponíveis</h1>

    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">
        @foreach ($jogos as $jogo)
            <div class="col-sm-4" style="margin-bottom: 5%">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="{{ asset('storage/'.$jogo->foto) }}" alt="Card image cap" style="width: 320px; height: 280px; align:center">
                    <div class="card-body" style="width: 320px">
                        <h5 class="card-title" style="text-align: center"><b>{{$jogo->titulo}}</b></h5>
                        <p class="card-text" style="text-align: center">{{$jogo->desenvolvedor->nome}}</p>
                        <div style="text-align: center;">
                            <a href="{{ route('jogo.show', $jogo->id) }}" class="btn btn-info">Editar</a>
                            <form method="post" action="{{ route('jogo.destroy', $jogo->id) }}" style="display: inline-block" onsubmit="return confirm('Confirma Exclusão do Jogo?'")>
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <input type="submit" class="btn btn-danger btn-sm" value="Excluir">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="row" style="text-align: center">
        {{ $jogos->links() }}
    </div>
    </div>
@endsection

resources/views/admin/pagina_jogo.blade.php
@extends('adminlte::page')

@section('title', 'FoxGames - Categorias')

@section('content_header')

@endsection

@section('content')

    <h1 style="text-align: center; margin-bottom: 2%">{{$jogo->titulo}}</h1>

    @if (session('status'))
        <div class="alert alert-success">
            {{ session('status') }}
        </div>
    @endif

    <div class="row">
        <div class="col-sm-6">
            <form method="post" action="{{ route('jogo.update', $jogo->id) }}" enctype="multipart/form-data">
                {{ method_field('put') }} 
                {{ csrf_field() }}
                <div class="container-fluid" style="margin-bottom: 5%">
                    <div class="col-sm-6">
                        <label for="titulo">Titulo:</label><br/>
                        <input type="text" name="titulo" id="titulo" value="{{$jogo->titulo}}"><br/>
                        <label for="preco">Preço:</label><br/>
                        <input type="text" name="preco" id="preco" value="{{number_format($jogo->preco, 2)}}">
                    </div>
                    <div class="col-sm-6">
                        <label for="desenvolvedor_id">Desenvolvedor:</label><br/>
                        <select class="form-control" id="desenvolvedor_id" name="desenvolvedor_id">
                            @foreach ($desenvolvedores as $desenvolvedor)
                                <option value="{{$desenvolvedor->id}}">
                                    {{$desenvolvedor->nome}}
                                </option>
                            @endforeach
                        </select>
                        <label for="foto">Foto:</label>
                        <input type="file" class="form-control" id="foto" name="foto">
                    </div>
                </div>

                <div class="col-sm-12" style="text-align: center; margin-bottom: 5%"> <input type="submit" value="Enviar" class="btn btn-success"> </div>
            </form>

            <div class="container-fluid">
                <div class="col-sm-6">
                    <label for="categoria">Adicionar Categoria:</label>
                    <form method="post" action="{{ route('jogo.add_categoria') }}">
                        {{ csrf_field() }}
                        <select class="form-control" 
                                    id="categoria_id" name="categoria_id">
                            @foreach ($categorias as $categoria)
                                <option value="{{$categoria->id}}">
                                    {{$categoria->nome}}
                                </option>
                            @endforeach
                        </select>
                        <input class="form-control" type="hidden" value="{{$jogo->id}}" id="jogo_id" name="jogo_id">
                        <input type="submit" class="btn btn-primary" style="float: right" value="Add">
                    </form>
                </div>
                <div class="col-sm-6">
                    <label for="idioma">Adicionar Idioma:</label>
                    <form method="post" action="{{ route('jogo.add_idioma') }}">
                        {{ csrf_field() }}
                        <select class="form-control" 
                                    id="idioma_id" name="idioma_id">
                            @foreach ($idiomas as $idioma)
                                <option value="{{$idioma->id}}">
                                    {{$idioma->nome}}
                                </option>
                            @endforeach
                        </select>
                        <input class="form-control" type="hidden" value="{{$jogo->id}}" id="jogo_id" name="jogo_id">
                        <input type="submit" class="btn btn-primary" style="float: right" value="Add">
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <table class="table">
                        <thead class="table-dark">
                            <tr>
                                <th>ID</th>
                                <th>Categoria</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($jogo->categorias as $categoria)
                                <tr><th>{{$categoria->nome}}</th></tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="col-sm-6">
                    <table class="table">
                        <thead class="table-dark">
                            <tr>
                                <th>ID</th>
                                <th>Idiomas</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($jogo->idiomas as $idioma)
                                <tr><th>{{$idioma->nome}}</th></tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <img src="../storage/{{ $jogo->foto }}" alt="jogo" style="width: 100%">
        </div>
    </div>

@endsection

@section('js')
  <script src="https://code.jquery.com/jquery-latest.min.js"></script>
  <script src="/js/jquery.mask.min.js"></script>

  <script>
    $(document).ready(function() {
      $('#preco').mask('#.###.##0,00', {reverse: true});
    });
  </script>  
@endsection

resources/views/admin/relJogos.blade.php
<div class="container-fluid">
    <h3 style="text-align: center">Fox Games</h3>
    <h5 style="text-align: center">Relatório de Jogos Cadastrados</h5>
    <h5 style="text-align: center">Data: {{date('d-m-Y')}} Hora:{{date('H:i:s')}}</h5>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <table class="table table-bordered table-sm">
            <thead class="thead-light">
                <tr>
                    <th>Jogo</th>
                    <th>Desenvolvedor</th>
                    <th>Preço R$:</th>
                    <th>Foto</th>
                </tr>
            </thead>
            <tbody>
                @foreach($jogos as $jogo)
                    <tr>
                        <td>{{$jogo->titulo}}</td>
                        <td>{{$jogo->desenvolvedor->nome}}</td>
                        <td style="text-align: right">{{number_format($jogo->preco, 2, ',', '.')}}</td>
                        <td style="text-align: center">
                            <img src="{{public_path('storage/'.$jogo->foto)}}" style="width:100px;height:60px">         
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
</div>